FROM openjdk:17-jdk-alpine

RUN apk --no-cache add git maven

RUN git clone https://github.com/Kosiyyu/demo-testing.git /app

WORKDIR /app

RUN cd demo-testing/test && \
    mvn package

CMD ["java", "-jar", "demo-testing/test/target/myapp.jar"]
