FROM openjdk:17-jdk-alpine

RUN apk --no-cache add git maven

RUN git clone https://github.com/Kosiyyu/demo-testing.git

WORKDIR /app/demo-testing/test

RUN mvn package

CMD ["java", "-jar", "/app/demo-testing/test/target/*.jar"]
