FROM openjdk:17-jdk-alpine

RUN apk --no-cache add git maven

WORKDIR /app

RUN git clone https://github.com/Kosiyyu/demo-testing.git

RUN cd demo-testing/test && \
    mvn package
    
RUN cd demo-testing/test/target && \
    pwd && \ 
    ls

CMD ["java", "-jar", "/app/demo-testing/test/target/test-1.0-SNAPSHOT.jar"]
