spring:
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: dev
    password:
    jpa:
        hibernate:
            ddl-auto: create-drop
            properties:
              hibernate:
                dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

